#!/bin/bash

start() {
    /srv/jarn/munin/bin/supervisord -c /srv/jarn/munin/etc/supervisord.conf
}

stop() {
    /srv/jarn/munin/bin/supervisorctl -c /srv/jarn/munin/etc/supervisord.conf shutdown
}

case "$1" in
  start)
    start
    exit $?
    ;;
  stop)
    stop
    exit $?
    ;;
esac

exit 1
