from Products.CMFCore.permissions import AddPortalContent
from Products.CMFCore.permissions import ModifyPortalContent

ADD_CONTENT_PERMISSION = AddPortalContent
EDIT_CONTENT_PERMISSION = ModifyPortalContent